- platform: template
  sensors:
    vacuum_fan_speed:
      friendly_name: Sugestyrke
      value_template: >-
        {{ state_attr("vacuum.r2_d2", "fan_speed") }}
      icon_template: >-
        mdi:network-strength-{{ state_attr("vacuum.r2_d2", "fan_speed") - 100 }}

    vacuum_r2_d2:
      entity_id: vacuum.r2_d2
      friendly_name_template: >-
        {{ state_attr("vacuum.r2_d2", "friendly_name") }}
      icon_template: >-
        {{ state_attr("vacuum.r2_d2", "battery_icon") }}
      value_template: >-
        {%- if is_state("vacuum.r2_d2", "docked") -%}
          Docked
        {%- elif is_state("vacuum.r2_d2", "cleaning") -%}
          Støvsuger
        {%- elif is_state("vacuum.r2_d2", "paused") -%}
          Pause
        {%- elif is_state("vacuum.r2_d2", "idle") -%}
          Tomgang
        {%- elif is_state("vacuum.r2_d2", "Charger disconnected") -%}
          Lader ikke
        {%- else -%}
          Ukendt
        {%- endif -%}
      attribute_templates:
        battery_level: >-
          {{ state_attr("vacuum.r2_d2", "battery_level") }}
        battery_icon: >-
          {{ state_attr("vacuum.r2_d2", "battery_icon") }}
        cleaning_time: >-
          {{ state_attr("vacuum.r2_d2", "cleaning_time") }}
        cleaned_area: >-
          {{ state_attr("vacuum.r2_d2", "cleaned_area") }}
        fan_speed: >-
          {%- set fan_speed = state_attr("vacuum.r2_d2", "fan_speed") | string -%}
          {{ state_attr("input_select.vacuum_power", "options")[fan_speed[2:] | int -1]  }}
        main_brush_left: >-
          {{ state_attr("vacuum.r2_d2", "main_brush_left") }}
        side_brush_left: >-
          {{ state_attr("vacuum.r2_d2", "side_brush_left") }}
        filter_left: >-
          {{ state_attr("vacuum.r2_d2", "filter_left") }}
        sensor_dirty_left: >-
          {{ state_attr("vacuum.r2_d2", "sensor_dirty_left") }}
        status: >-
          {%- if is_state_attr("vacuum.r2_d2", "status", "Charging") and is_state_attr("vacuum.r2_d2", "battery_level", 100) -%}
            Opladt
          {%- elif is_state_attr("vacuum.r2_d2", "status", "Charging") -%}
            Oplader
          {%- elif is_state_attr("vacuum.r2_d2", "status", "Segment cleaning") -%}
            Støvsuger i et rum
          {%- elif is_state_attr("vacuum.r2_d2", "status", "Returning home") -%}
            Kører hjem
          {%- else -%}
            {{ state_attr("vacuum.r2_d2", "status") }}
          {%- endif -%}
