#- alias: "Update DuckDNS"
#  trigger:
#    platform: time_pattern
#    hours: "/6"
#  action:
#    - service: shell_command.update_duckdns

# Load dynamic list at start
- alias: "Load lister ved start af HA"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: shell_command.select_set_options
    - service: shell_command.var_set_values

    - service: script.refresh_movies
    - service: script.refresh_covers

    - service: vacuum.set_fan_speed
      data_template:
        entity_id: vacuum.r2_d2
        fan_speed: >-
          {{ states("var.vacuum_default_fanspeed") }} 

# Change log level
- alias: "Set log niveau"
  trigger:
    platform: state
    entity_id: input_select.log_level
  action:
    - service: logger.set_default_level
      data_template:
        level: >-
          {{ states("input_select.log_level") }}

# Restart IKEA gateways and HomeAssistant ( Main and Slave )
- alias: "Restart Gateways & HA"
  trigger:
    # Trigger - time equals time from GUI
    - platform: template
      value_template: >-
        {{ states('sensor.time') == (state_attr("input_datetime.restart_time", "timestamp") | int | timestamp_custom('%H:%M', false)) }}

  action:
    # Turn off Gateway_2
    # Wait 30 seconds
    - service: switch.turn_off
      entity_id: switch.gateway_2
    - delay: "00:00:30"

    # Turn on Gate_2
    # Wait 10  minutes
    - service: switch.turn_on
      entity_id: switch.gateway_2
    - delay: "00:10:00"

    # Turn off Gateway_1
    # Wait 30 seconds
    - service: switch.turn_off
      entity_id: switch.gateway_1
    - delay: "00:00:30"

    # Turn on Gate_1
    # Wait 10 minutes
    - service: switch.turn_on
      entity_id: switch.gateway_1
    - delay: "00:10:00"

    # Restart the slave HA
    # Wait 5 minutes
    - service: script.restart_ha_slave
    - delay: "00:05:00"

    # Restart the main HA
    - service: script.restart_ha_main
    - delay: "00:05:00"

    # Turn off patio.... ???
    - service: light.turn_off
      entity_id: light.havegang