# Send the new suction setting to the vacuum
- alias: "Skift sugestyrke på støvsugeren"
  trigger:
    # Trigger - when a suction setting is choosen
    platform: state
    entity_id: input_select.vacuum_power
  action:
    service: vacuum.set_fan_speed
    data_template:
      entity_id: vacuum.r2_d2
      # Find the index of the selected option (index starting from 1)
      # Append this digit to 10 - ex. 101
      fan_speed: >-
        {% for needle in state_attr("input_select.vacuum_power", "options") %}
          {% if needle == states("input_select.vacuum_power") %}
            10{{ loop.index }}
          {% endif %}
        {%- endfor %}

- alias: "Sugestyrke slider"
  trigger:
    platform: state
    entity_id: input_number.vacuum_fan_speed
  action:
    service: vacuum.set_fan_speed
    data_template:
      entity_id: vacuum.r2_d2
      fan_speed: >-
        {{ states("input_number.vacuum_fan_speed") | int }}

# We have changed the suction settings in the app
# and wish to match the new setting
- alias: "Match suge-menuen til støvsugeren"
  trigger:
    # Trigger - new suction
    # and at start of HA
    - platform: state
      entity_id: sensor.vacuum_fan_speed
    - platform: homeassistant
      event: start
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.vacuum_power
        # Get the last digit of the vacuums settings ( ex. 103 = 3 )
        # Substract 1 and use this value as index on the options
        option: >-
          {{ state_attr("input_select.vacuum_power", "options")[state_attr("vacuum.r2_d2", "fan_speed") - 101] }}
    - service: input_number.set_value
      data_template:
        entity_id: input_number.vacuum_fan_speed
        value: >-
          {{ state_attr("vacuum.r2_d2", "fan_speed") }}