title: Netværk
icon: mdi:power-settings
panel: true
cards:
  - type: custom:layout-card
    layout: vertical
    max_columns: 3
    min_width: 33%
    max_width: 99%
    cards:
      - !include cards/system/dockermon.yaml
      - break

      - !include cards/system/restart_gateways.yaml
      - break

      - !include cards/system/all_automations.yaml
